<?php
$parameters = array(
	'db_driver' => 'pdo_mysql',
	'db_host' => 'localhost',
	'db_table_prefix' => null,
	'db_port' => '3306',
	'db_name' => 'marketing',
	'db_user' => 'admin',
	'db_password' => '123',
	'db_backup_tables' => 0,
	'db_backup_prefix' => 'bak_',
	'db_server_version' => '5.5.5-10.1.26-MariaDB-0+deb9u1',
	'mailer_from_name' => 'Vongkol HENG',
	'mailer_from_email' => 'hengvongkol@gmail.com',
	'mailer_transport' => 'mail',
	'mailer_host' => null,
	'mailer_port' => null,
	'mailer_user' => null,
	'mailer_password' => null,
	'mailer_encryption' => null,
	'mailer_auth_mode' => null,
	'mailer_spool_type' => 'memory',
	'mailer_spool_path' => '%kernel.root_dir%/spool',
	'secret_key' => '09beb8de1165662dd1d1225529870515dcba135e8bdda358903be728b4d03153',
	'site_url' => 'http://localhost/marketing/index.php',
);
