<?php
$parameters = array(
	'db_driver' => 'pdo_mysql',
	'db_host' => 'localhost',
	'db_table_prefix' => null,
	'db_port' => '3306',
	'db_name' => 'mautic',
	'db_user' => 'admin',
	'db_password' => '123',
	'db_backup_tables' => 1,
	'db_backup_prefix' => 'bak_',
	'db_server_version' => '5.7.20',
	'mailer_from_name' => 'vichey sor',
	'mailer_from_email' => 'sorvichey096@gmail.com',
	'mailer_transport' => 'mail',
	'mailer_host' => null,
	'mailer_port' => null,
	'mailer_user' => '%',
	'mailer_password' => '123',
	'mailer_encryption' => null,
	'mailer_auth_mode' => null,
	'mailer_spool_type' => 'file',
	'mailer_spool_path' => '%kernel.root_dir%/spool',
	'secret_key' => '585c61044ed0b59ecd8d463e1866cc6013a6726dedb51514a021560ef416ca12',
	'site_url' => 'http://localhost/mautic',
);
